# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: npm start
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common
      - /app/backend/node_modules

    environment:
      PORT: 3000
      DB_USER: log2_user
      DB_HOST: db
      DB_PASSWORD: 
      DB_SCHEMA: log2
      JWT_SECRET: 
      GOOGLE_CLIENT_ID: 
    ports: 
      - 3001:3000
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend
  #   command: npm start
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: log2_user
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: log2
      TZ: 'Europe/Stockholm'
    ports: 
      - 3006:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  db_webadmin:
    image: adminer
    ports:
      - 8080:8080